### ISSUE TITLE
not working on opera browser

### ISSUE THREAD

**Issue by ohad131** [OlegWock/anori#39] opened 2023-04-25 08:40 UTC
anori not working with opera browser. new tabs open on default tab (speed dial).

**Comment by OlegWock** [comment] 2023-04-25 09:49
Yeah, it seems opera disabled ability for extension to set custom new tab. I'll add workaround in next version, but currently extension doesn't work on Opera unfortunately 

Closing as duplicate of https://github.com/OlegWock/anori/issues/26

**Closed by OlegWock** 2023-04-25 09:49 UTC
