### ISSUE TITLE
New feature: Anori account

### ISSUE THREAD

**Issue by Autumnnx** [OlegWock/anori#197] opened 2024-06-18 23:54 UTC
I'd like to suggest an option to create an account for the extension or link it with the browser account so that the personal settings of the extension can be saved automatically and syncronized in every device or computer that has the extension linked with the same account, so you don't have to add any other shortcuts in the other devices you use or export the settings from device to device, which makes it easier to save, syncronize, and use the same personal settings for the extension at anytime and anywhere.

**Comment by OlegWock** [comment] 2024-06-20 09:53
Hello! This is already on the roadmap. But creating separate accounts system with cloud sync is just a lot of work (and then ongoing costs for server) and I currently don't have enough free time for Anori to work on this. 

Closing as duplicate of #47

**Closed by OlegWock** 2024-06-20 09:53 UTC
