### ISSUE TITLE
Wrong time in Recently closed widget

### ISSUE THREAD

**Issue by zumosik** [OlegWock/anori#169] opened 2024-03-18 19:24 UTC
![image](https://github.com/OlegWock/anori/assets/86283476/dfd28459-3267-4dbf-a9e6-2207d2481a23)
Why is here 54 years?

**Comment by slayernominee** [comment] 2024-03-19 14:08
54 years is 1970 the start year of unix time, so the timestamp is probably 0. which either is caused by your browser for whatever reason or the widget has some fallback of using 0 if it cant get the timestamp of something along the line

**Comment by OlegWock** [comment] 2024-04-12 14:25
This should be fixed in v1.18.0 (you should get this update automatically by this time), so I'm closing this issue

**Closed by OlegWock** 2024-04-12 14:25 UTC
Labels: Resolved in next release
